name: Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the code
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Set up a C++ environment
    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y g++ clang libncurses-dev

    # Step 3: Build the program
    - name: Build the program
      run: clang++ -std=c++17 *.cpp -o fcard -lncurses

    # Step 4: Test the program
    - name: Install coverage
      run: pip3 install coverage

    - name: Run tests
      run: python3 -m unittest discover -s tests
